pcf(1) [""["pcf-VERSION"]]

# NAME

pcf - blah blah

# SYNOPSIS

pcf [options] [files]

# DESCRIPTION

blah blah

# AUTHORS

Maintained by Dakota Walsh <kota at nilsu.org>.
Up-to-date sources can be found at https://git.sr.ht/~kota/pcf

# COPYRIGHT

Copyright 2019 Dakota Walsh

License GPLv3+ GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.
